### PR TITLE
Version 1.0

### PR DESCRIPTION
**Pull request by vkdnjdldnjsw**
1. Normal Gallery
2. Automatically tag image
3. Synchronizer
4. Image View
5. Show category
6. Word/Selective search to find images with tags

### CODE REVIEW

**Review by gunhoo — APPROVED** [review]
Awesome!!!
We did it

**Review by Yewon000 — APPROVED** [review]
good

**Review by KangSoYeon — APPROVED** [review]
oh yeah~~~

**Review by MyungSeKyo — APPROVED** [review]
Badass

**Pull request merged**
